# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-03-03T14:14:23+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class HeartBeat(BaseModel):
    __root__: str = Field(
        ..., description='A simple heartBeat message (Hello)', title='heartBeat'
    )
