# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-04-04T15:44:36+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class HostPublicKey(BaseModel):
    host: Optional[str] = None
    publicKey: Optional[str] = None
