# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-03-05T14:50:50+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class ProjectList(BaseModel):
    pass

    class Config:
        extra = Extra.allow
