# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-03-03T14:14:22+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class ProjectList(BaseModel):
    pass

    class Config:
        extra = Extra.allow
