# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-04-08T09:08:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class ProjectBuildTarget(BaseModel):
    pass

    class Config:
        extra = Extra.allow
