# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-03-02T19:41:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ProjectPath(BaseModel):
    projectName: Optional[str] = None
    projectDir: Optional[str] = None
