# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2021-11-03T16:41:55+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class TaskStatus(BaseModel):
    target: str
    progress: int
    dependencies: Optional[List[str]] = Field(
        None, description='An array of dependent tasks'
    )
