genSchema:
  pydantic: {}
  ajv:
    ajvOptions:
      strict: True
      allErrors: True
genExamples:
  pythonExamples: {}
  javaScriptExamples: {}
  mockServerExamples: {}
  mithrilExamples: {}
  fastApiExamples: {}
genHttpRoutes:
  httpRouteUtils: {}
  mithrilConnectors: {}
  fastApiRoutes: {}
