genSchema:
  pydantic: {}
  ajv:
    ajvOptions:
      strict: True
      allErrors: True
genExamples:
  pythonExamples: {}
  javaScriptExamples: {}
  mockServiceWorkers: {}
genHttpRoutes:
  mithrilConnectors: {}
  fastApiRoutes: {}
